/// This is copied from Cargokit (which is the official way to use it currently)
/// Details: https://fzyzcjy.github.io/flutter_rust_bridge/manual/integrate/builtin

import java.nio.file.Paths
import org.apache.tools.ant.taskdefs.condition.Os

CargoKitPlugin.file = buildscript.sourceFile

apply plugin: CargoKitPlugin

class CargoKitExtension {
    String manifestDir; // Relative path to folder containing Cargo.toml
    String libname; // Library name within Cargo.toml. Must be a cdylib
}

abstract class CargoKitBuildTask extends DefaultTask {

    @Input
    String buildMode

    @Input
    String buildDir

    @Input
    String outputDir

    @Input
    String ndkVersion

    @Input
    String sdkDirectory

    @Input
    int compileSdkVersion;

    @Input
    int minSdkVersion;

    @Input
    String pluginFile

    @Input
    List<String> targetPlatforms

    @TaskAction
    def build() {
        if (project.cargokit.manifestDir == null) {
            throw new GradleException("Property 'manifestDir' must be set on cargokit extension");
        }

        if (project.cargokit.libname == null) {
            throw new GradleException("Property 'libname' must be set on cargokit extension");
        }

        def executableName = Os.isFamily(Os.FAMILY_WINDOWS) ? "run_build_tool.cmd" : "run_build_tool.sh"
        def path = Paths.get(new File(pluginFile).parent, "..", executableName);

        def manifestDir = Paths.get(project.buildscript.sourceFile.parent, project.cargokit.manifestDir)

        def rootProjectDir = project.rootProject.projectDir

        if (!Os.isFamily(Os.FAMILY_WINDOWS)) {
            project.exec {
                commandLine 'chmod', '+x', path
            }
        }

        project.exec {
            executable path
            args "build-gradle"
            environment "CARGOKIT_ROOT_PROJECT_DIR", rootProjectDir
            environment "CARGOKIT_TOOL_TEMP_DIR", "${buildDir}/build_tool"
            environment "CARGOKIT_MANIFEST_DIR", manifestDir
            environment "CARGOKIT_CONFIGURATION", buildMode
            environment "CARGOKIT_TARGET_TEMP_DIR", buildDir
            environment "CARGOKIT_OUTPUT_DIR", outputDir
            environment "CARGOKIT_NDK_VERSION", ndkVersion
            environment "CARGOKIT_SDK_DIR", sdkDirectory
            environment "CARGOKIT_COMPILE_SDK_VERSION", compileSdkVersion
            environment "CARGOKIT_MIN_SDK_VERSION", minSdkVersion
            environment "CARGOKIT_TARGET_PLATFORMS", targetPlatforms.join(",")
            environment "CARGOKIT_JAVA_HOME", System.properties['java.home']
        }
    }
}

class CargoKitPlugin implements Plugin<Project> {

    static String file;

    private static void whenEvaluated(Project p, Closure c) {
        if (p.state.executed) {
            c()
        } else {
            p.afterEvaluate { c() }
        }
    }

    @Override
    void apply(Project project) {
        project.extensions.create("cargokit", CargoKitExtension)

        whenEvaluated(project.rootProject) {
            def appProject = project.rootProject.findProject(':app')
            if (appProject == null) {
                return
            }

            whenEvaluated(appProject) {
                if (!appProject.plugins.hasPlugin('com.android.application')) {
                    return
                }

                setupCargoKitBuild(project, appProject)
            }
        }
    }

    private static void setupCargoKitBuild(Project project, def appProject) {
        whenEvaluated(project) {
            def cargoBuildDir = "${project.buildDir}/build"

            project.android.libraryVariants.all { variant ->
                final buildType = variant.buildType.name

                def cargoOutputDir = "${project.buildDir}/jniLibs/${buildType}"
                def jniLibs = project.android.sourceSets.maybeCreate(buildType).jniLibs
                jniLibs.srcDir(new File(cargoOutputDir))

                // 默认目标平台（仅 arm64）
                def platforms = ["android-arm64"]

                def ndkVersion = appProject.extensions.android.ndkVersion
                def sdkDirObj = appProject.extensions.android.sdkDirectory
                def sdkDirectory = sdkDirObj != null ? sdkDirObj.toString() : ""
                def minSdkVersion = 26
                if (appProject.extensions.android.defaultConfig.minSdkVersion != null) {
                    minSdkVersion = appProject.extensions.android.defaultConfig.minSdkVersion.apiLevel
                }
                def compileSdkVersion = 35
                if (appProject.extensions.android.compileSdkVersion != null) {
                    def compileSdkVersionString = appProject.extensions.android.compileSdkVersion.toString()
                    compileSdkVersion = compileSdkVersionString.replaceAll("android-", "") as int
                }

                def taskName = "cargokitCargoBuild${project.cargokit.libname.capitalize()}${buildType.capitalize()}"

                if (project.tasks.findByName(taskName)) {
                    return
                }

                def task = project.tasks.create(taskName, CargoKitBuildTask.class) {
                    it.buildMode = variant.buildType.name
                    it.buildDir = cargoBuildDir
                    it.outputDir = cargoOutputDir
                    it.ndkVersion = ndkVersion != null ? ndkVersion : "27.0.12077973"
                    it.sdkDirectory = sdkDirectory
                    it.minSdkVersion = minSdkVersion
                    it.compileSdkVersion = compileSdkVersion
                    it.targetPlatforms = platforms
                    it.pluginFile = CargoKitPlugin.file
                }

                project.tasks.findByName("merge${buildType.capitalize()}NativeLibs")?.dependsOn task
                task.outputs.upToDateWhen { false }
            }
        }
    }
}
